name: Deploy to portainer

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Login into ghcr
        run: echo ${{ secrets.TOKEN }} | docker login https://ghcr.io -u ${{github.actor}} --password-stdin

      - name: Build, tag, and push image to ghcr
        env:
          REGISTRY: ghcr.io/${{ github.repository_owner }}
          IMAGE_NAME: ${{ github.repository }}
        run: |
          docker build . -t $IMAGE_NAME
          docker image tag $IMAGE_NAME $REGISTRY/$IMAGE_NAME:${{ github.sha }}
          docker image push $REGISTRY/$IMAGE_NAME:${{ github.sha }}

      - name: Webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}?tag=${{ github.sha }}